import { spawnSync } from "node:child_process";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";

import { compactKeys, compactStrings } from "./compact.mjs";
import {
  generatedDataDirectory,
  generatedLicensePath,
  generatedManifestPath,
  generatedProvidersDirectory,
  generatedSourceDirectory,
  packageDirectory,
  providerDeclarationsDirectory,
  repositoryDirectory,
  rootLicensePath,
} from "./paths.mjs";

const result = spawnSync(
  "mix",
  [
    "llm_db.npm.export",
    "--output",
    generatedDataDirectory,
  ],
  {
    cwd: repositoryDirectory,
    encoding: "utf8",
  },
);

if (result.status !== 0) {
  process.stderr.write(result.stderr);
  process.stdout.write(result.stdout);
  process.exit(result.status ?? 1);
}

process.stdout.write(result.stdout);

const manifestSource = await readFile(generatedManifestPath, "utf8");
const manifest = JSON.parse(manifestSource);
const providerIds = Object.keys(manifest.providers).sort();
const providers = await Promise.all(
  providerIds.map(async (providerId) =>
    JSON.parse(
      await readFile(
        `${generatedProvidersDirectory}/${providerId}.json`,
        "utf8",
      ),
    ),
  ),
);
const sharedKeys = compactKeys(providers);
const sharedStrings = compactStrings(providers);

validateManifest(manifest, providerIds);

await Promise.all([
  mkdir(generatedSourceDirectory, { recursive: true }),
  mkdir(providerDeclarationsDirectory, { recursive: true }),
  copyFile(rootLicensePath, generatedLicensePath),
]);

await Promise.all([
  writeFile(
    new URL("../src/generated/manifest.ts", import.meta.url),
    manifestModule(manifestSource, providerIds),
  ),
  writeFile(
    new URL("../src/generated/provider-loaders.ts", import.meta.url),
    loaderModule(providerIds),
  ),
  writeFile(
    new URL("../src/generated/compact-keys.ts", import.meta.url),
    compactValuesModule("compactKeys", sharedKeys),
  ),
  writeFile(
    new URL("../src/generated/compact-strings.ts", import.meta.url),
    compactValuesModule("compactStrings", sharedStrings),
  ),
  writeFile(
    new URL("../src/generated/snapshot-contract.d.ts", import.meta.url),
    snapshotContractModule(providers),
  ),
  ...providerIds.map((providerId) =>
    writeFile(
      new URL(`../src/providers/${providerId}.d.ts`, import.meta.url),
      providerDeclaration(),
    ),
  ),
]);

console.log(
  `Generated TypeScript loaders for ${providerIds.length} provider shards ` +
    `in ${packageDirectory}.`,
);

function manifestModule(source, providerIds) {
  const providerUnion = providerIds.map(JSON.stringify).join(" | ");

  return `// Generated by scripts/generate.mjs. Do not edit.
import type { Manifest } from "../types.js";

export type KnownProviderId = ${providerUnion};

export const manifest = ${source.trim()} as Manifest;
`;
}

function loaderModule(providerIds) {
  const entries = providerIds
    .map(
      (providerId) =>
        `  ${JSON.stringify(providerId)}: () => ` +
        `import("../providers/${providerId}.js").then((module) => module.default),`,
    )
    .join("\n");

  return `// Generated by scripts/generate.mjs. Do not edit.
import type { ProviderLoader } from "../types.js";
import type { KnownProviderId } from "./manifest.js";

export const providerLoaders: Readonly<
  Record<KnownProviderId, ProviderLoader>
> = {
${entries}
};
`;
}

function compactValuesModule(name, values) {
  return `// Generated by scripts/generate.mjs. Do not edit.
export const ${name}: readonly string[] = ${JSON.stringify(values)};
`;
}

function providerDeclaration() {
  return `import type { ProviderCatalog } from "../types.js";

declare const provider: ProviderCatalog;
export default provider;
`;
}

function snapshotContractModule(providers) {
  const pricingComponents = providers.flatMap((provider) => [
    ...(provider.pricing_defaults?.components ?? []),
    ...Object.values(provider.models).flatMap(
      (model) => model.pricing?.components ?? [],
    ),
  ]);
  const embeddingCapabilities = providers.flatMap((provider) =>
    Object.values(provider.models)
      .map((model) => model.capabilities?.embeddings)
      .filter(
        (embeddings) =>
          embeddings !== null && typeof embeddings === "object",
      ),
  );

  if (pricingComponents.length === 0 || embeddingCapabilities.length === 0) {
    throw new Error("Canonical NPM contract samples are missing.");
  }

  return `// Generated by scripts/generate.mjs. Do not edit.
import type {
  EmbeddingCapability,
  PricingComponent,
} from "../types.js";

type AssertAssignable<Expected, Actual extends Expected> = Actual;

type CanonicalPricingComponent = ${observedObjectType(
    pricingComponents,
    new Set(["kind", "unit"]),
  )};

type CanonicalEmbeddingCapability = ${observedObjectType(
    embeddingCapabilities,
  )};

export type PricingComponentContract = AssertAssignable<
  PricingComponent,
  CanonicalPricingComponent
>;

export type EmbeddingCapabilityContract = AssertAssignable<
  EmbeddingCapability,
  CanonicalEmbeddingCapability
>;
`;
}

function observedObjectType(values, literalKeys = new Set(), indent = "") {
  const keys = [...new Set(values.flatMap((value) => Object.keys(value)))].sort();

  if (keys.length === 0) {
    return "Readonly<Record<string, never>>";
  }

  const childIndent = `${indent}  `;
  const fields = keys.map((key) => {
    const presentValues = values
      .filter((value) => Object.hasOwn(value, key))
      .map((value) => value[key]);
    const optional = presentValues.length < values.length ? "?" : "";
    const valueType = observedValueType(
      presentValues,
      literalKeys.has(key),
      childIndent,
    );

    return `${childIndent}readonly ${JSON.stringify(key)}${optional}: ${valueType};`;
  });

  return `{\n${fields.join("\n")}\n${indent}}`;
}

function observedValueType(values, useStringLiterals, indent) {
  const types = [];
  const groups = Map.groupBy(values, (value) => {
    if (value === null) return "null";
    if (Array.isArray(value)) return "array";
    return typeof value;
  });

  for (const [kind, group] of [...groups].sort(([left], [right]) =>
    left.localeCompare(right),
  )) {
    switch (kind) {
      case "array": {
        const items = group.flat();
        types.push(
          items.length === 0
            ? "readonly never[]"
            : `readonly (${observedValueType(items, false, indent)})[]`,
        );
        break;
      }
      case "boolean":
      case "number":
        types.push(kind);
        break;
      case "null":
        types.push("null");
        break;
      case "object":
        types.push(observedObjectType(group, new Set(), indent));
        break;
      case "string":
        types.push(
          useStringLiterals
            ? [...new Set(group)].sort().map(JSON.stringify).join(" | ")
            : "string",
        );
        break;
      default:
        throw new Error(`Unsupported canonical JSON value type: ${kind}.`);
    }
  }

  return [...new Set(types)].join(" | ");
}

function validateManifest(value, providerIds) {
  if (
    value === null ||
    typeof value !== "object" ||
    value.format_version !== 1 ||
    typeof value.snapshot_id !== "string" ||
    !/^[a-f0-9]{64}$/.test(value.snapshot_id)
  ) {
    throw new Error("Elixir produced an invalid NPM shard manifest.");
  }

  if (providerIds.length !== value.provider_count) {
    throw new Error("NPM shard manifest provider count is inconsistent.");
  }
}
